### ISSUE TITLE
Check if we are using: style checkers, code formatters, syntax checkers

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#11]
Its automated in the github action. Link: https://github.com/lyonva/ScheduleBot/blob/main/.github/workflows/python-app.yml

If we do not: **create another issue**
We need this as part of the rubric.

**Comment by lyonva** [comment]
So I checked and we are actually using flake8. It is both style enforcer and it checks for syntax errors. So we are good.

**Comment by ConnorS1110** [comment]
This is working correctly
