### ISSUE TITLE
Write 2 page report

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#15]
From project 1 description:

Write a 2 page pdf on the commnection between the items in that rubric and the Linux Kernel best practices. And that document to your repo as docs/proj1rubricComments.pdf. Write the that pdf using [this template](https://www.overleaf.com/latex/templates/association-for-computing-machinery-acm-sig-proceedings-template/bmvfhcdnxfty)
- Not "nearly" this template. This tempalte. Learn Latex. Hit: use (overleaf)[https://www.overleaf.com/].

Probably we do it on the last day.

**Comment by lyonva** [comment]
This has been written and its on docs/proj1Report.pdf
Please check

**Comment by vasuagrawal19** [comment]
The document looks solid. I think we can move ahead with it.
