### ISSUE TITLE
Create/Update sub-readme.md

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#28]
In [doc](https://github.com/lyonva/ScheduleBot/tree/main/doc): VERY short just describing what we use to generate doc
In [test](https://github.com/lyonva/ScheduleBot/tree/main/test): ditto
In [src](https://github.com/lyonva/ScheduleBot/tree/main/src): Just the general code structure

**Comment by ConnorS1110** [comment]
These files were not needed are were removed from the repo
