### ISSUE TITLE
Finish self-code documentation

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#4]
Please leave a comment here when you finish this. When everyone does, we check and close the issue.

**Comment by ConnorS1110** [comment]
My functions have been documented

**Comment by vasuagrawal19** [comment]
My functions have been documented.

**Comment by Capt-Fluffy-Bug** [comment]
My functions have been documented

**Comment by Muhammad-Alahmadi** [comment]
My functions have been documented.

**Comment by lyonva** [comment]
My functions have been documented. 1 to go.

**Comment by ashwith161** [comment]
My functions have been documented.

**Comment by lyonva** [comment]
I checked the online documentation generated by pdoc3. Everything looks great.
However, we are missing documentation for Event_Type:
https://lyonva.github.io/ScheduleBot/event_type.html

**Comment by ashwith161** [comment]
updated the documentation for Event_Type

**Comment by lyonva** [comment]
I see it now. Then I think this is good to close.
Someone else please check as well and we can close this.

**Comment by ConnorS1110** [comment]
The documentation looks good
