### ISSUE TITLE
Finish self-code test cases

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#5]
Finish test cases for **your own code**. Leave a comment when yours are ready.

**Comment by lyonva** [comment]
I wrote test cases for my code.

**Comment by Capt-Fluffy-Bug** [comment]
I wrote some basic test cases for my code

**Comment by Muhammad-Alahmadi** [comment]
I wrote test cases for my code.

**Comment by ashwith161** [comment]
I wrote some test cases for my code

**Comment by ConnorS1110** [comment]
I wrote test cases for my code

**Comment by ConnorS1110** [comment]
Everyone's test cases look good
