### ISSUE TITLE
Update proj1rubric.md

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#6]
Go to https://github.com/lyonva/ScheduleBot/blob/main/doc/proj1rubric.md and update it
Do this when we are close to submitting the project.

**Comment by lyonva** [comment]
Rubric has been updated as of this comment. Totaling 201 points. Someone please check. If you thing we should have less/more at any point, you are welcome to change (and update the points total please).

**Comment by ConnorS1110** [comment]
Rubric looks good
