### ISSUE TITLE
Do mini-tutorials for each command

### ISSUE THREAD

**Issue by lyonva** [lyonva/ScheduleBot#7]
Probably in documentation and/or readme
From rubric: Docs: how: for common use cases X,Y,Z mini-tutorials showing worked examples on how to do X,Y,Z

**Comment by ConnorS1110** [comment]
Added GIFs for working commands

**Comment by lyonva** [comment]
Looks good and I like the GIFS. The small issue is that the bot name/pic is outdated, but I think its good to go.
